#!/usr/bin/env bash
# Operation and PID file

file="/var/run/myscript.pid"

if [ ! -e "$file" ]; then
  touch "$file"
fi

sleep 2 &

echo "$!" > "$file"

# Console.log I hate the kill command, deletes the file and exits  when receiving a SIGTERM or SIGQUIT signal
trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT

# print why you no love me?! when receiving a SIGINT sign
trap "echo why you no love me?!" SIGINT

while true; do
  echo "To infinity and beyond"
  sleep 2
done
